<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

// php artisan db:seed --class=SparepartRequestSeeder

class MachineSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Pastikan UserSeeder dijalankan terlebih dahulu untuk mengisi data PLP
        // Jika belum yakin, bisa ditambahkan call seeder di sini (tidak disarankan untuk produksi besar)
        // $this->call(UserSeeder::class);

        // Ambil semua ID pengguna dengan role 'plp'
        $plpUserIds = DB::table('users')->where('role', 'plp')->pluck('id')->toArray();

        // Beri peringatan jika tidak ada pengguna PLP yang ditemukan
        if (empty($plpUserIds)) {
            $this->command->warn('Tidak ada pengguna dengan role "plp" ditemukan. Harap jalankan UserSeeder terlebih dahulu atau pastikan pengguna PLP sudah ada.');
            return;
        }

        $machines = [
            [
                'name' => 'Mesin Bubut DoALL',
                'type' => 'Bubut DoALL',
                'code' => 'BU.01',
                'inventory_number' => null,
                'year_acquired' => 2017,
                'status' => 'inactive',
                'condition' => 'damaged',
                'length' => 191.4,
                'width' => 85.65,
                'height' => 178.78,
                'power' => '5 kW',
                'supplier' => 'PT Sumber Teknik',
                'image' => null,
                'description' => null,
                'repair_complexity' => 5,
                'created_by' => 1,
            ],
            [
                'name' => 'Mesin Bubut DoALL',
                'type' => 'Bubut DoALL',
                'code' => 'BU.02',
                'inventory_number' => null,
                'year_acquired' => 2021,
                'status' => 'active',
                'condition' => 'good',
                'length' => 166.64,
                'width' => 205.42,
                'height' => 198.94,
                'power' => '1.5 kW',
                'supplier' => 'CV Maju Jaya',
                'image' => null,
                'description' => null,
                'repair_complexity' => 3,
                'created_by' => 1,
            ],
            [
                'name' => 'Mesin Bubut DoALL',
                'type' => 'Bubut DoALL',
                'code' => 'BU.03',
                'inventory_number' => null,
                'year_acquired' => 2024,
                'status' => 'active',
                'condition' => 'good',
                'length' => 150.31,
                'width' => 184.3,
                'height' => 215.76,
                'power' => '3 HP',
                'supplier' => 'UD Teknik Lancar',
                'image' => null,
                'description' => null,
                'repair_complexity' => 1,
                'created_by' => 1,
            ],
            [
                'name' => 'Mesin Bubut DoALL',
                'type' => 'Bubut DoALL',
                'code' => 'BU.04',
                'inventory_number' => null,
                'year_acquired' => 2021,
                'status' => 'active',
                'condition' => 'good',
                'length' => 276.99,
                'width' => 99.07,
                'height' => 132.05,
                'power' => '2.2 kW',
                'supplier' => 'PT Mesin Abadi',
                'image' => null,
                'description' => null,
                'repair_complexity' => 3,
                'created_by' => 1,
            ],
            [
                'name' => 'Mesin Bubut DoALL',
                'type' => 'Bubut DoALL',
                'code' => 'BU.05',
                'inventory_number' => null,
                'year_acquired' => 2024,
                'status' => 'active',
                'condition' => 'good',
                'length' => 235.99,
                'width' => 156.48,
                'height' => 222.28,
                'power' => '2.2 kW',
                'supplier' => 'PT Mesin Abadi',
                'image' => null,
                'description' => null,
                'repair_complexity' => 4,
                'created_by' => 1,
            ],
            [
                'name' => 'Mesin Bubut DoALL',
                'type' => 'Bubut DoALL',
                'code' => 'BU.06',
                'inventory_number' => null,
                'year_acquired' => 2010,
                'status' => 'active',
                'condition' => 'good',
                'length' => 235.28,
                'width' => 179.33,
                'height' => 144.04,
                'power' => '5 kW',
                'supplier' => 'PT Sumber Teknik',
                'image' => null,
                'description' => null,
                'repair_complexity' => 3,
                'created_by' => 1,
            ],
            [
                'name' => 'Mesin Bubut DoALL',
                'type' => 'Bubut DoALL',
                'code' => 'BU.07',
                'inventory_number' => null,
                'year_acquired' => 2022,
                'status' => 'active',
                'condition' => 'good',
                'length' => 189.1,
                'width' => 229.39,
                'height' => 156.76,
                'power' => '1.5 kW',
                'supplier' => 'PT Mesin Abadi',
                'image' => null,
                'description' => null,
                'repair_complexity' => 5,
                'created_by' => 1,
            ],
            [
                'name' => 'Mesin Bubut DoALL',
                'type' => 'Bubut DoALL',
                'code' => 'BU.08',
                'inventory_number' => null,
                'year_acquired' => 2014,
                'status' => 'active',
                'condition' => 'good',
                'length' => 191.33,
                'width' => 94.34,
                'height' => 161.8,
                'power' => '2.2 kW',
                'supplier' => 'PT Mesin Abadi',
                'image' => null,
                'description' => null,
                'repair_complexity' => 2,
                'created_by' => 1,
            ],
            [
                'name' => 'Mesin Bubut AJ310E',
                'type' => 'Bubut AJ310E',
                'code' => 'BU.10',
                'inventory_number' => null,
                'year_acquired' => 2020,
                'status' => 'active',
                'condition' => 'good',
                'length' => 251.14,
                'width' => 254.49,
                'height' => 203.98,
                'power' => '2.2 kW',
                'supplier' => 'UD Teknik Lancar',
                'image' => null,
                'description' => null,
                'repair_complexity' => 3,
                'created_by' => 1,
            ],
            [
                'name' => 'Mesin Bubut AJ310E',
                'type' => 'Bubut AJ310E',
                'code' => 'BU.11',
                'inventory_number' => null,
                'year_acquired' => 2018,
                'status' => 'inactive',
                'condition' => 'damaged',
                'length' => 250.9,
                'width' => 70.33,
                'height' => 109.06,
                'power' => '5 kW',
                'supplier' => 'UD Teknik Lancar',
                'image' => null,
                'description' => null,
                'repair_complexity' => 2,
                'created_by' => 1,
            ],
            [
                'name' => 'Mesin Bubut AJ310E',
                'type' => 'Bubut AJ310E',
                'code' => 'BU.12',
                'inventory_number' => null,
                'year_acquired' => 2019,
                'status' => 'inactive',
                'condition' => 'damaged',
                'length' => 238.72,
                'width' => 248.42,
                'height' => 295.79,
                'power' => '2.2 kW',
                'supplier' => 'CV Maju Jaya',
                'image' => null,
                'description' => null,
                'repair_complexity' => 1,
                'created_by' => 1,
            ],
            [
                'name' => 'Mesin Bubut AJ310E',
                'type' => 'Bubut AJ310E',
                'code' => 'BU.13',
                'inventory_number' => null,
                'year_acquired' => 2023,
                'status' => 'inactive',
                'condition' => 'damaged',
                'length' => 120.13,
                'width' => 132.36,
                'height' => 61.49,
                'power' => '5 kW',
                'supplier' => 'PT Mesin Abadi',
                'image' => null,
                'description' => null,
                'repair_complexity' => 2,
                'created_by' => 1,
            ],
            [
                'name' => 'Mesin Bubut AJ310E',
                'type' => 'Bubut AJ310E',
                'code' => 'BU.14',
                'inventory_number' => null,
                'year_acquired' => 2015,
                'status' => 'inactive',
                'condition' => 'damaged',
                'length' => 223.14,
                'width' => 255.34,
                'height' => 239.76,
                'power' => '1.5 kW',
                'supplier' => 'UD Teknik Lancar',
                'image' => null,
                'description' => null,
                'repair_complexity' => 1,
                'created_by' => 1,
            ],
            [
                'name' => 'Mesin Bubut MAWItec',
                'type' => 'Bubut MAWItec',
                'code' => 'BU.15',
                'inventory_number' => null,
                'year_acquired' => 2010,
                'status' => 'active',
                'condition' => 'good',
                'length' => 177.82,
                'width' => 254.46,
                'height' => 53.55,
                'power' => '7.5 HP',
                'supplier' => 'UD Teknik Lancar',
                'image' => null,
                'description' => null,
                'repair_complexity' => 1,
                'created_by' => 1,
            ],
            [
                'name' => 'Mesin Bubut MAWItec',
                'type' => 'Bubut MAWItec',
                'code' => 'BU.16',
                'inventory_number' => null,
                'year_acquired' => 2022,
                'status' => 'active',
                'condition' => 'good',
                'length' => 139.79,
                'width' => 73.89,
                'height' => 52.41,
                'power' => '2.2 kW',
                'supplier' => 'PT Mesin Abadi',
                'image' => null,
                'description' => null,
                'repair_complexity' => 5,
                'created_by' => 1,
            ],
            [
                'name' => 'Mesin Bubut AJ200E',
                'type' => 'Bubut AJ200E',
                'code' => 'BU.17',
                'inventory_number' => null,
                'year_acquired' => 2011,
                'status' => 'active',
                'condition' => 'good',
                'length' => 266.49,
                'width' => 132.34,
                'height' => 217.8,
                'power' => '3 HP',
                'supplier' => 'PT Mesin Abadi',
                'image' => null,
                'description' => null,
                'repair_complexity' => 2,
                'created_by' => 1,
            ],
            [
                'name' => 'Mesin Bubut AJ200E',
                'type' => 'Bubut AJ200E',
                'code' => 'BU.18',
                'inventory_number' => null,
                'year_acquired' => 2015,
                'status' => 'inactive',
                'condition' => 'damaged',
                'length' => 236.3,
                'width' => 156.4,
                'height' => 272.02,
                'power' => '2.2 kW',
                'supplier' => 'PT Mesin Abadi',
                'image' => null,
                'description' => null,
                'repair_complexity' => 2,
                'created_by' => 1,
            ],
            [
                'name' => 'Mesin Bubut Geminis',
                'type' => 'Bubut Geminis',
                'code' => 'BU.19',
                'inventory_number' => null,
                'year_acquired' => 2019,
                'status' => 'active',
                'condition' => 'good',
                'length' => 277.65,
                'width' => 215.07,
                'height' => 97.56,
                'power' => '2.2 kW',
                'supplier' => 'CV Maju Jaya',
                'image' => null,
                'description' => null,
                'repair_complexity' => 3,
                'created_by' => 1,
            ],
            [
                'name' => 'Mesin Bubut Geminis',
                'type' => 'Bubut Geminis',
                'code' => 'BU.20',
                'inventory_number' => null,
                'year_acquired' => 2022,
                'status' => 'active',
                'condition' => 'good',
                'length' => 233.03,
                'width' => 128.12,
                'height' => 231.6,
                'power' => '5 kW',
                'supplier' => 'CV Maju Jaya',
                'image' => null,
                'description' => null,
                'repair_complexity' => 1,
                'created_by' => 1,
            ],
            [
                'name' => 'Mesin Bubut Geminis',
                'type' => 'Bubut Geminis',
                'code' => 'BU.21',
                'inventory_number' => null,
                'year_acquired' => 2012,
                'status' => 'active',
                'condition' => 'good',
                'length' => 267.25,
                'width' => 285.18,
                'height' => 280.26,
                'power' => '5 kW',
                'supplier' => 'PT Sumber Teknik',
                'image' => null,
                'description' => null,
                'repair_complexity' => 3,
                'created_by' => 1,
            ],
            [
                'name' => 'Mesin Bubut Krisbow',
                'type' => 'Bubut Krisbow',
                'code' => 'BU 22',
                'inventory_number' => null,
                'year_acquired' => 2012,
                'status' => 'active',
                'condition' => 'good',
                'length' => 194.88,
                'width' => 233.97,
                'height' => 163.96,
                'power' => '2.2 kW',
                'supplier' => 'PT Mesin Abadi',
                'image' => null,
                'description' => null,
                'repair_complexity' => 5,
                'created_by' => 1,
            ],
            [
                'name' => 'Mesin Bubut Krisbow',
                'type' => 'Bubut Krisbow',
                'code' => 'BU 23',
                'inventory_number' => null,
                'year_acquired' => 2024,
                'status' => 'active',
                'condition' => 'good',
                'length' => 90.68,
                'width' => 284.69,
                'height' => 128.8,
                'power' => '2.2 kW',
                'supplier' => 'CV Maju Jaya',
                'image' => null,
                'description' => null,
                'repair_complexity' => 4,
                'created_by' => 1,
            ],
            [
                'name' => 'Mesin Bubut Krisbow',
                'type' => 'Bubut Krisbow',
                'code' => 'BU 24',
                'inventory_number' => null,
                'year_acquired' => 2012,
                'status' => 'active',
                'condition' => 'good',
                'length' => 50.89,
                'width' => 62.88,
                'height' => 132.89,
                'power' => '7.5 HP',
                'supplier' => 'PT Sumber Teknik',
                'image' => null,
                'description' => null,
                'repair_complexity' => 4,
                'created_by' => 1,
            ],
            [
                'name' => 'Mesin Bubut Bemato',
                'type' => 'Bubut Bemato',
                'code' => 'BU 25',
                'inventory_number' => null,
                'year_acquired' => 2016,
                'status' => 'active',
                'condition' => 'good',
                'length' => 243.28,
                'width' => 218.26,
                'height' => 131.31,
                'power' => '5 kW',
                'supplier' => 'CV Maju Jaya',
                'image' => null,
                'description' => null,
                'repair_complexity' => 2,
                'created_by' => 1,
            ],
            [
                'name' => 'Mesin Bubut Bemato',
                'type' => 'Bubut Bemato',
                'code' => 'BU 26',
                'inventory_number' => null,
                'year_acquired' => 2023,
                'status' => 'active',
                'condition' => 'good',
                'length' => 176.76,
                'width' => 127.88,
                'height' => 80.94,
                'power' => '3 HP',
                'supplier' => 'PT Sumber Teknik',
                'image' => null,
                'description' => null,
                'repair_complexity' => 5,
                'created_by' => 1,
            ],
            [
                'name' => 'Mesin Bubut Bemato',
                'type' => 'Bubut Bemato',
                'code' => 'BU 27',
                'inventory_number' => null,
                'year_acquired' => 2017,
                'status' => 'active',
                'condition' => 'good',
                'length' => 147.26,
                'width' => 158.15,
                'height' => 274.65,
                'power' => '7.5 HP',
                'supplier' => 'PT Mesin Abadi',
                'image' => null,
                'description' => null,
                'repair_complexity' => 5,
                'created_by' => 1,
            ],
            [
                'name' => 'Mesin Bubut Bemato',
                'type' => 'Bubut Bemato',
                'code' => 'BU 28',
                'inventory_number' => null,
                'year_acquired' => 2013,
                'status' => 'active',
                'condition' => 'good',
                'length' => 250.02,
                'width' => 267.04,
                'height' => 89.43,
                'power' => '5 kW',
                'supplier' => 'UD Teknik Lancar',
                'image' => null,
                'description' => null,
                'repair_complexity' => 3,
                'created_by' => 1,
            ],
            [
                'name' => 'Mesin Bubut Bemato',
                'type' => 'Bubut Bemato',
                'code' => 'BU 29',
                'inventory_number' => null,
                'year_acquired' => 2023,
                'status' => 'active',
                'condition' => 'good',
                'length' => 272.82,
                'width' => 230.52,
                'height' => 159.49,
                'power' => '5 kW',
                'supplier' => 'PT Mesin Abadi',
                'image' => null,
                'description' => null,
                'repair_complexity' => 5,
                'created_by' => 1,
            ],
            [
                'name' => 'Mesin Bubut Bemato',
                'type' => 'Bubut Bemato',
                'code' => 'BU 30',
                'inventory_number' => null,
                'year_acquired' => 2020,
                'status' => 'active',
                'condition' => 'good',
                'length' => 220.55,
                'width' => 151.84,
                'height' => 60.05,
                'power' => '2.2 kW',
                'supplier' => 'PT Sumber Teknik',
                'image' => null,
                'description' => null,
                'repair_complexity' => 2,
                'created_by' => 1,
            ],
            [
                'name' => 'Mesin Freis Fehlmann',
                'type' => 'Freis Fehlmann',
                'code' => 'FR.01',
                'inventory_number' => null,
                'year_acquired' => 2019,
                'status' => 'active',
                'condition' => 'good',
                'length' => 91.45,
                'width' => 204.88,
                'height' => 287.32,
                'power' => '3 HP',
                'supplier' => 'UD Teknik Lancar',
                'image' => null,
                'description' => null,
                'repair_complexity' => 4,
                'created_by' => 1,
            ],
            [
                'name' => 'Mesin Freis Fehlmann',
                'type' => 'Freis Fehlmann',
                'code' => 'FR.02',
                'inventory_number' => null,
                'year_acquired' => 2012,
                'status' => 'active',
                'condition' => 'good',
                'length' => 174.8,
                'width' => 285.83,
                'height' => 91.21,
                'power' => '5 kW',
                'supplier' => 'CV Maju Jaya',
                'image' => null,
                'description' => null,
                'repair_complexity' => 5,
                'created_by' => 1,
            ],
            [
                'name' => 'Mesin Freis Fehlmann',
                'type' => 'Freis Fehlmann',
                'code' => 'FR.03',
                'inventory_number' => null,
                'year_acquired' => 2010,
                'status' => 'active',
                'condition' => 'good',
                'length' => 291.01,
                'width' => 181.04,
                'height' => 287.38,
                'power' => '7.5 HP',
                'supplier' => 'PT Sumber Teknik',
                'image' => null,
                'description' => null,
                'repair_complexity' => 1,
                'created_by' => 1,
            ],
            [
                'name' => 'Mesin Freis Fehlmann',
                'type' => 'Freis Fehlmann',
                'code' => 'FR.04',
                'inventory_number' => null,
                'year_acquired' => 2017,
                'status' => 'inactive',
                'condition' => 'damaged',
                'length' => 104.95,
                'width' => 78.23,
                'height' => 213.64,
                'power' => '2.2 kW',
                'supplier' => 'CV Maju Jaya',
                'image' => null,
                'description' => null,
                'repair_complexity' => 2,
                'created_by' => 1,
            ],
            [
                'name' => 'Mesin Freis Aciera F3',
                'type' => 'Freis Aciera F3',
                'code' => 'FR.05',
                'inventory_number' => null,
                'year_acquired' => 2014,
                'status' => 'active',
                'condition' => 'good',
                'length' => 161.76,
                'width' => 299.89,
                'height' => 166.57,
                'power' => '5 kW',
                'supplier' => 'UD Teknik Lancar',
                'image' => null,
                'description' => null,
                'repair_complexity' => 3,
                'created_by' => 1,
            ],
            [
                'name' => 'Mesin Freis Aciera F3',
                'type' => 'Freis Aciera F3',
                'code' => 'FR.06',
                'inventory_number' => null,
                'year_acquired' => 2022,
                'status' => 'active',
                'condition' => 'good',
                'length' => 232.81,
                'width' => 231.64,
                'height' => 216.89,
                'power' => '2.2 kW',
                'supplier' => 'UD Teknik Lancar',
                'image' => null,
                'description' => null,
                'repair_complexity' => 5,
                'created_by' => 1,
            ],
            [
                'name' => 'Mesin Freis Aciera F3',
                'type' => 'Freis Aciera F3',
                'code' => 'FR.07',
                'inventory_number' => null,
                'year_acquired' => 2022,
                'status' => 'inactive',
                'condition' => 'damaged',
                'length' => 247.49,
                'width' => 53.34,
                'height' => 96.07,
                'power' => '5 kW',
                'supplier' => 'PT Mesin Abadi',
                'image' => null,
                'description' => null,
                'repair_complexity' => 4,
                'created_by' => 1,
            ],
            [
                'name' => 'Mesin Freis Aciera F3',
                'type' => 'Freis Aciera F3',
                'code' => 'FR.08',
                'inventory_number' => null,
                'year_acquired' => 2021,
                'status' => 'inactive',
                'condition' => 'damaged',
                'length' => 117.49,
                'width' => 175.18,
                'height' => 193.0,
                'power' => '5 kW',
                'supplier' => 'UD Teknik Lancar',
                'image' => null,
                'description' => null,
                'repair_complexity' => 2,
                'created_by' => 1,
            ],
            [
                'name' => 'Mesin Freis Ajax "00"',
                'type' => 'Freis Ajax "00"',
                'code' => 'FR.09',
                'inventory_number' => null,
                'year_acquired' => 2020,
                'status' => 'inactive',
                'condition' => 'damaged',
                'length' => 69.6,
                'width' => 282.68,
                'height' => 90.8,
                'power' => '7.5 HP',
                'supplier' => 'PT Sumber Teknik',
                'image' => null,
                'description' => null,
                'repair_complexity' => 2,
                'created_by' => 1,
            ],
            [
                'name' => 'Mesin Freis Ajax "00"',
                'type' => 'Freis Ajax "00"',
                'code' => 'FR.10',
                'inventory_number' => null,
                'year_acquired' => 2016,
                'status' => 'inactive',
                'condition' => 'damaged',
                'length' => 215.34,
                'width' => 270.91,
                'height' => 134.97,
                'power' => '1.5 kW',
                'supplier' => 'UD Teknik Lancar',
                'image' => null,
                'description' => null,
                'repair_complexity' => 1,
                'created_by' => 1,
            ],
            [
                'name' => 'Mesin Freis Ajax 2AMK5',
                'type' => 'Freis Ajax 2AMK5',
                'code' => 'FR.11',
                'inventory_number' => null,
                'year_acquired' => 2016,
                'status' => 'active',
                'condition' => 'good',
                'length' => 84.56,
                'width' => 144.73,
                'height' => 203.2,
                'power' => '5 kW',
                'supplier' => 'PT Mesin Abadi',
                'image' => null,
                'description' => null,
                'repair_complexity' => 1,
                'created_by' => 1,
            ],
            [
                'name' => 'Mesin Freis Ajax 2AMK5',
                'type' => 'Freis Ajax 2AMK5',
                'code' => 'FR.12',
                'inventory_number' => null,
                'year_acquired' => 2014,
                'status' => 'active',
                'condition' => 'good',
                'length' => 241.18,
                'width' => 58.59,
                'height' => 291.35,
                'power' => '3 HP',
                'supplier' => 'UD Teknik Lancar',
                'image' => null,
                'description' => null,
                'repair_complexity' => 1,
                'created_by' => 1,
            ],
            [
                'name' => 'Mesin Freis Ajax 2AMK5',
                'type' => 'Freis Ajax 2AMK5',
                'code' => 'FR.13',
                'inventory_number' => null,
                'year_acquired' => 2010,
                'status' => 'active',
                'condition' => 'good',
                'length' => 232.66,
                'width' => 108.78,
                'height' => 176.99,
                'power' => '5 kW',
                'supplier' => 'PT Sumber Teknik',
                'image' => null,
                'description' => null,
                'repair_complexity' => 3,
                'created_by' => 1,
            ],
            [
                'name' => 'Mesin Freis Ajax 2AMK5',
                'type' => 'Freis Ajax 2AMK5',
                'code' => 'FR.14',
                'inventory_number' => null,
                'year_acquired' => 2012,
                'status' => 'active',
                'condition' => 'good',
                'length' => 93.0,
                'width' => 93.78,
                'height' => 80.01,
                'power' => '7.5 HP',
                'supplier' => 'UD Teknik Lancar',
                'image' => null,
                'description' => null,
                'repair_complexity' => 2,
                'created_by' => 1,
            ],
            [
                'name' => 'Mesin Freis Ajax 2AMK5',
                'type' => 'Freis Ajax 2AMK5',
                'code' => 'FR.15',
                'inventory_number' => null,
                'year_acquired' => 2011,
                'status' => 'active',
                'condition' => 'good',
                'length' => 81.56,
                'width' => 113.55,
                'height' => 118.33,
                'power' => '1.5 kW',
                'supplier' => 'PT Mesin Abadi',
                'image' => null,
                'description' => null,
                'repair_complexity' => 2,
                'created_by' => 1,
            ],
            [
                'name' => 'Mesin Freis Ajax 2AMK5',
                'type' => 'Freis Ajax 2AMK5',
                'code' => 'FR.16',
                'inventory_number' => null,
                'year_acquired' => 2017,
                'status' => 'active',
                'condition' => 'good',
                'length' => 51.87,
                'width' => 239.22,
                'height' => 86.1,
                'power' => '3 HP',
                'supplier' => 'CV Maju Jaya',
                'image' => null,
                'description' => null,
                'repair_complexity' => 5,
                'created_by' => 1,
            ],
            [
                'name' => 'Mesin Freis Lagun FU125',
                'type' => 'Freis Lagun FU125',
                'code' => 'FR.17',
                'inventory_number' => null,
                'year_acquired' => 2015,
                'status' => 'active',
                'condition' => 'good',
                'length' => 120.22,
                'width' => 90.74,
                'height' => 179.93,
                'power' => '2.2 kW',
                'supplier' => 'PT Mesin Abadi',
                'image' => null,
                'description' => null,
                'repair_complexity' => 4,
                'created_by' => 1,
            ],
            [
                'name' => 'Mesin Freis Lagun FU125',
                'type' => 'Freis Lagun FU125',
                'code' => 'FR.18',
                'inventory_number' => null,
                'year_acquired' => 2020,
                'status' => 'active',
                'condition' => 'good',
                'length' => 225.93,
                'width' => 61.37,
                'height' => 215.7,
                'power' => '1.5 kW',
                'supplier' => 'PT Sumber Teknik',
                'image' => null,
                'description' => null,
                'repair_complexity' => 4,
                'created_by' => 1,
            ],
            [
                'name' => 'Mesin Freis Lagun FU125',
                'type' => 'Freis Lagun FU125',
                'code' => 'FR.19',
                'inventory_number' => null,
                'year_acquired' => 2012,
                'status' => 'active',
                'condition' => 'good',
                'length' => 227.0,
                'width' => 158.62,
                'height' => 282.37,
                'power' => '2.2 kW',
                'supplier' => 'CV Maju Jaya',
                'image' => null,
                'description' => null,
                'repair_complexity' => 1,
                'created_by' => 1,
            ],
            [
                'name' => 'Mesin Freis Fehlmann',
                'type' => 'Freis Fehlmann',
                'code' => 'FR.20',
                'inventory_number' => null,
                'year_acquired' => 2024,
                'status' => 'active',
                'condition' => 'good',
                'length' => 212.63,
                'width' => 228.98,
                'height' => 196.75,
                'power' => '2.2 kW',
                'supplier' => 'CV Maju Jaya',
                'image' => null,
                'description' => null,
                'repair_complexity' => 2,
                'created_by' => 1,
            ],
            [
                'name' => 'Mesin Freis Fehlmann',
                'type' => 'Freis Fehlmann',
                'code' => 'FR.21',
                'inventory_number' => null,
                'year_acquired' => 2022,
                'status' => 'active',
                'condition' => 'good',
                'length' => 112.8,
                'width' => 203.89,
                'height' => 73.95,
                'power' => '2.2 kW',
                'supplier' => 'PT Mesin Abadi',
                'image' => null,
                'description' => null,
                'repair_complexity' => 5,
                'created_by' => 1,
            ],
            [
                'name' => 'Mesin Bor Metabo S24',
                'type' => 'Bor Metabo S24',
                'code' => 'BO.01',
                'inventory_number' => null,
                'year_acquired' => 2010,
                'status' => 'inactive',
                'condition' => 'damaged',
                'length' => 60.69,
                'width' => 224.83,
                'height' => 149.67,
                'power' => '1.5 kW',
                'supplier' => 'UD Teknik Lancar',
                'image' => null,
                'description' => null,
                'repair_complexity' => 2,
                'created_by' => 1,
            ],
            [
                'name' => 'Mesin Bor Metabo S24',
                'type' => 'Bor Metabo S24',
                'code' => 'BO.02',
                'inventory_number' => null,
                'year_acquired' => 2020,
                'status' => 'inactive',
                'condition' => 'damaged',
                'length' => 183.51,
                'width' => 106.16,
                'height' => 135.18,
                'power' => '7.5 HP',
                'supplier' => 'PT Sumber Teknik',
                'image' => null,
                'description' => null,
                'repair_complexity' => 3,
                'created_by' => 1,
            ],
            [
                'name' => 'Mesin Bor Metabo T15',
                'type' => 'Bor Metabo T15',
                'code' => 'BO.03',
                'inventory_number' => null,
                'year_acquired' => 2012,
                'status' => 'inactive',
                'condition' => 'damaged',
                'length' => 77.71,
                'width' => 254.56,
                'height' => 242.14,
                'power' => '1.5 kW',
                'supplier' => 'PT Sumber Teknik',
                'image' => null,
                'description' => null,
                'repair_complexity' => 4,
                'created_by' => 1,
            ],
            [
                'name' => 'Mesin Bor Metabo T15',
                'type' => 'Bor Metabo T15',
                'code' => 'BO.04',
                'inventory_number' => null,
                'year_acquired' => 2011,
                'status' => 'inactive',
                'condition' => 'damaged',
                'length' => 73.67,
                'width' => 220.82,
                'height' => 181.12,
                'power' => '3 HP',
                'supplier' => 'PT Sumber Teknik',
                'image' => null,
                'description' => null,
                'repair_complexity' => 4,
                'created_by' => 1,
            ],
            [
                'name' => 'Mesin Bor Magnum',
                'type' => 'Bor Magnum',
                'code' => 'BO.05',
                'inventory_number' => null,
                'year_acquired' => 2022,
                'status' => 'active',
                'condition' => 'good',
                'length' => 260.71,
                'width' => 269.93,
                'height' => 83.91,
                'power' => '2.2 kW',
                'supplier' => 'UD Teknik Lancar',
                'image' => null,
                'description' => null,
                'repair_complexity' => 5,
                'created_by' => 1,
            ],
            [
                'name' => 'Mesin Bor Magnum',
                'type' => 'Bor Magnum',
                'code' => 'BO.06',
                'inventory_number' => null,
                'year_acquired' => 2020,
                'status' => 'active',
                'condition' => 'good',
                'length' => 135.27,
                'width' => 196.3,
                'height' => 286.8,
                'power' => '2.2 kW',
                'supplier' => 'PT Sumber Teknik',
                'image' => null,
                'description' => null,
                'repair_complexity' => 4,
                'created_by' => 1,
            ],
            [
                'name' => 'Mesin Bor Krisbow',
                'type' => 'Bor Krisbow',
                'code' => 'BO.07',
                'inventory_number' => null,
                'year_acquired' => 2016,
                'status' => 'active',
                'condition' => 'good',
                'length' => 174.19,
                'width' => 175.06,
                'height' => 210.66,
                'power' => '1.5 kW',
                'supplier' => 'UD Teknik Lancar',
                'image' => null,
                'description' => null,
                'repair_complexity' => 1,
                'created_by' => 1,
            ],
            [
                'name' => 'Mesin Bor Krisbow',
                'type' => 'Bor Krisbow',
                'code' => 'BO.08',
                'inventory_number' => null,
                'year_acquired' => 2010,
                'status' => 'active',
                'condition' => 'good',
                'length' => 271.78,
                'width' => 74.55,
                'height' => 243.31,
                'power' => '3 HP',
                'supplier' => 'UD Teknik Lancar',
                'image' => null,
                'description' => null,
                'repair_complexity' => 1,
                'created_by' => 1,
            ],
            [
                'name' => 'Mesin Sekrap W.B6351',
                'type' => 'Sekrap W.B6351',
                'code' => 'SE.01',
                'inventory_number' => null,
                'year_acquired' => 2021,
                'status' => 'inactive',
                'condition' => 'damaged',
                'length' => 257.57,
                'width' => 65.72,
                'height' => 124.3,
                'power' => '1.5 kW',
                'supplier' => 'UD Teknik Lancar',
                'image' => null,
                'description' => null,
                'repair_complexity' => 4,
                'created_by' => 1,
            ],
            [
                'name' => 'Mesin Sekrap W.B6351',
                'type' => 'Sekrap W.B6351',
                'code' => 'SE.02',
                'inventory_number' => null,
                'year_acquired' => 2018,
                'status' => 'active',
                'condition' => 'good',
                'length' => 82.69,
                'width' => 286.86,
                'height' => 254.71,
                'power' => '5 kW',
                'supplier' => 'UD Teknik Lancar',
                'image' => null,
                'description' => null,
                'repair_complexity' => 1,
                'created_by' => 1,
            ],
            [
                'name' => 'Mesin Sekrap W.BC6063',
                'type' => 'Sekrap W.BC6063',
                'code' => 'SE.03',
                'inventory_number' => null,
                'year_acquired' => 2019,
                'status' => 'active',
                'condition' => 'good',
                'length' => 133.5,
                'width' => 212.67,
                'height' => 82.68,
                'power' => '7.5 HP',
                'supplier' => 'CV Maju Jaya',
                'image' => null,
                'description' => null,
                'repair_complexity' => 2,
                'created_by' => 1,
            ],
            [
                'name' => 'Mesin Sekrap W.BC6063',
                'type' => 'Sekrap W.BC6063',
                'code' => 'SE.04',
                'inventory_number' => null,
                'year_acquired' => 2016,
                'status' => 'active',
                'condition' => 'good',
                'length' => 298.09,
                'width' => 219.16,
                'height' => 112.57,
                'power' => '1.5 kW',
                'supplier' => 'PT Sumber Teknik',
                'image' => null,
                'description' => null,
                'repair_complexity' => 3,
                'created_by' => 1,
            ],
            [
                'name' => 'Mesin Gerinda datar Reform',
                'type' => 'Gerinda datar Reform',
                'code' => 'GD.01',
                'inventory_number' => null,
                'year_acquired' => 2010,
                'status' => 'active',
                'condition' => 'good',
                'length' => 204.11,
                'width' => 288.22,
                'height' => 121.72,
                'power' => '5 kW',
                'supplier' => 'PT Mesin Abadi',
                'image' => null,
                'description' => null,
                'repair_complexity' => 1,
                'created_by' => 1,
            ],
            [
                'name' => 'Mesin Gerinda datar Reform',
                'type' => 'Gerinda datar Reform',
                'code' => 'GD.02',
                'inventory_number' => null,
                'year_acquired' => 2022,
                'status' => 'active',
                'condition' => 'good',
                'length' => 119.67,
                'width' => 152.32,
                'height' => 161.1,
                'power' => '1.5 kW',
                'supplier' => 'UD Teknik Lancar',
                'image' => null,
                'description' => null,
                'repair_complexity' => 3,
                'created_by' => 1,
            ],
            [
                'name' => 'Mesin Gerinda datar',
                'type' => 'Gerinda datar',
                'code' => 'GD.03',
                'inventory_number' => null,
                'year_acquired' => 2023,
                'status' => 'inactive',
                'condition' => 'damaged',
                'length' => 97.46,
                'width' => 101.1,
                'height' => 51.28,
                'power' => '1.5 kW',
                'supplier' => 'CV Maju Jaya',
                'image' => null,
                'description' => null,
                'repair_complexity' => 5,
                'created_by' => 1,
            ],
            [
                'name' => 'Mesin Gerinda datar',
                'type' => 'Gerinda datar',
                'code' => 'GD.04',
                'inventory_number' => null,
                'year_acquired' => 2020,
                'status' => 'inactive',
                'condition' => 'damaged',
                'length' => 181.68,
                'width' => 71.56,
                'height' => 146.74,
                'power' => '5 kW',
                'supplier' => 'CV Maju Jaya',
                'image' => null,
                'description' => null,
                'repair_complexity' => 1,
                'created_by' => 1,
            ],
            [
                'name' => 'Mesin Gerinda Silinder',
                'type' => 'Gerinda Silinder',
                'code' => 'GS.01',
                'inventory_number' => null,
                'year_acquired' => 2015,
                'status' => 'active',
                'condition' => 'good',
                'length' => 274.85,
                'width' => 260.14,
                'height' => 291.78,
                'power' => '2.2 kW',
                'supplier' => 'CV Maju Jaya',
                'image' => null,
                'description' => null,
                'repair_complexity' => 1,
                'created_by' => 1,
            ],
            [
                'name' => 'Mesin Gerinda Silinder',
                'type' => 'Gerinda Silinder',
                'code' => 'GS.02',
                'inventory_number' => null,
                'year_acquired' => 2021,
                'status' => 'active',
                'condition' => 'good',
                'length' => 90.48,
                'width' => 223.2,
                'height' => 214.68,
                'power' => '2.2 kW',
                'supplier' => 'PT Sumber Teknik',
                'image' => null,
                'description' => null,
                'repair_complexity' => 1,
                'created_by' => 1,
            ],
            [
                'name' => 'Mesin Gerinda Silinder',
                'type' => 'Gerinda Silinder',
                'code' => 'GS.03',
                'inventory_number' => null,
                'year_acquired' => 2023,
                'status' => 'active',
                'condition' => 'good',
                'length' => 274.37,
                'width' => 116.66,
                'height' => 278.47,
                'power' => '2.2 kW',
                'supplier' => 'PT Mesin Abadi',
                'image' => null,
                'description' => null,
                'repair_complexity' => 4,
                'created_by' => 1,
            ],
            [
                'name' => 'Mesin Gerinda Silinder',
                'type' => 'Gerinda Silinder',
                'code' => 'GS.04',
                'inventory_number' => null,
                'year_acquired' => 2015,
                'status' => 'inactive',
                'condition' => 'damaged',
                'length' => 67.76,
                'width' => 72.23,
                'height' => 104.23,
                'power' => '7.5 HP',
                'supplier' => 'PT Mesin Abadi',
                'image' => null,
                'description' => null,
                'repair_complexity' => 3,
                'created_by' => 1,
            ],
            [
                'name' => 'Mesin Press Tool Saxon',
                'type' => 'Press Tool Saxon',
                'code' => 'PT 01',
                'inventory_number' => null,
                'year_acquired' => 2014,
                'status' => 'active',
                'condition' => 'good',
                'length' => 271.65,
                'width' => 289.27,
                'height' => 97.38,
                'power' => '3 HP',
                'supplier' => 'UD Teknik Lancar',
                'image' => null,
                'description' => null,
                'repair_complexity' => 1,
                'created_by' => 1,
            ],
            [
                'name' => 'Mesin Press Tool Jiang Su Yang Li',
                'type' => 'Press Tool Jiang Su Yang Li',
                'code' => 'PT 02',
                'inventory_number' => null,
                'year_acquired' => 2018,
                'status' => 'active',
                'condition' => 'good',
                'length' => 229.65,
                'width' => 230.55,
                'height' => 176.4,
                'power' => '3 HP',
                'supplier' => 'CV Maju Jaya',
                'image' => null,
                'description' => null,
                'repair_complexity' => 3,
                'created_by' => 1,
            ],
            [
                'name' => 'Mesin Moulding Arburg Allrounder 420C',
                'type' => 'Moulding Arburg Allrounder 420C',
                'code' => 'MD 01',
                'inventory_number' => null,
                'year_acquired' => 2012,
                'status' => 'inactive',
                'condition' => 'damaged',
                'length' => 139.17,
                'width' => 143.57,
                'height' => 160.47,
                'power' => '5 kW',
                'supplier' => 'PT Sumber Teknik',
                'image' => null,
                'description' => null,
                'repair_complexity' => 3,
                'created_by' => 1,
            ],
            [
                'name' => 'Mesin Moulding Woojin TE170 GS',
                'type' => 'Moulding Woojin TE170 GS',
                'code' => 'MD 02',
                'inventory_number' => null,
                'year_acquired' => 2022,
                'status' => 'active',
                'condition' => 'good',
                'length' => 274.07,
                'width' => 66.17,
                'height' => 72.46,
                'power' => '2.2 kW',
                'supplier' => 'UD Teknik Lancar',
                'image' => null,
                'description' => null,
                'repair_complexity' => 5,
                'created_by' => 1,
            ],
            [
                'name' => 'Mesin CNC Mori Seiki SL-25',
                'type' => 'CNC Mori Seiki SL-25',
                'code' => 'CNCT 01',
                'inventory_number' => null,
                'year_acquired' => 2023,
                'status' => 'active',
                'condition' => 'good',
                'length' => 68.9,
                'width' => 128.88,
                'height' => 252.3,
                'power' => '3 HP',
                'supplier' => 'UD Teknik Lancar',
                'image' => null,
                'description' => null,
                'repair_complexity' => 1,
                'created_by' => 1,
            ],
            [
                'name' => 'Mesin CNC Mori Seiki MV-40M',
                'type' => 'CNC Mori Seiki MV-40M',
                'code' => 'CNCM 01',
                'inventory_number' => null,
                'year_acquired' => 2017,
                'status' => 'active',
                'condition' => 'good',
                'length' => 207.44,
                'width' => 64.92,
                'height' => 50.86,
                'power' => '3 HP',
                'supplier' => 'UD Teknik Lancar',
                'image' => null,
                'description' => null,
                'repair_complexity' => 5,
                'created_by' => 1,
            ],
            [
                'name' => 'Mesin CNC Lagun MC-750',
                'type' => 'CNC Lagun MC-750',
                'code' => 'CNCM 02',
                'inventory_number' => null,
                'year_acquired' => 2012,
                'status' => 'active',
                'condition' => 'good',
                'length' => 139.21,
                'width' => 171.9,
                'height' => 79.73,
                'power' => '2.2 kW',
                'supplier' => 'PT Mesin Abadi',
                'image' => null,
                'description' => null,
                'repair_complexity' => 3,
                'created_by' => 1,
            ],
            [
                'name' => 'Mesin CNC Kinsen HY-312M',
                'type' => 'CNC Kinsen HY-312M',
                'code' => 'CNCM 04',
                'inventory_number' => null,
                'year_acquired' => 2013,
                'status' => 'inactive',
                'condition' => 'damaged',
                'length' => 169.33,
                'width' => 246.57,
                'height' => 243.86,
                'power' => '2.2 kW',
                'supplier' => 'UD Teknik Lancar',
                'image' => null,
                'description' => null,
                'repair_complexity' => 1,
                'created_by' => 1,
            ],
            [
                'name' => 'Mesin CNC Kinsen Kenyo VS655',
                'type' => 'CNC Kinsen Kenyo VS655',
                'code' => 'CNCM 05',
                'inventory_number' => null,
                'year_acquired' => 2019,
                'status' => 'inactive',
                'condition' => 'damaged',
                'length' => 205.23,
                'width' => 202.46,
                'height' => 92.32,
                'power' => '3 HP',
                'supplier' => 'CV Maju Jaya',
                'image' => null,
                'description' => null,
                'repair_complexity' => 4,
                'created_by' => 1,
            ],
            [
                'name' => 'Mesin CNC Mori Seiki NLX2500Y',
                'type' => 'CNC Mori Seiki NLX2500Y',
                'code' => 'CNCTM 01',
                'inventory_number' => null,
                'year_acquired' => 2020,
                'status' => 'active',
                'condition' => 'good',
                'length' => 111.5,
                'width' => 66.38,
                'height' => 239.24,
                'power' => '1.5 kW',
                'supplier' => 'UD Teknik Lancar',
                'image' => null,
                'description' => null,
                'repair_complexity' => 1,
                'created_by' => 1,
            ],
            [
                'name' => 'Mesin EDM H-DS025',
                'type' => 'EDM H-DS025',
                'code' => 'EDM 01',
                'inventory_number' => null,
                'year_acquired' => 2017,
                'status' => 'inactive',
                'condition' => 'damaged',
                'length' => 71.61,
                'width' => 294.82,
                'height' => 264.08,
                'power' => '1.5 kW',
                'supplier' => 'CV Maju Jaya',
                'image' => null,
                'description' => null,
                'repair_complexity' => 3,
                'created_by' => 1,
            ],
            [
                'name' => 'Mesin Wirecut Mark-10W',
                'type' => 'Wirecut Mark-10W',
                'code' => 'WC 01',
                'inventory_number' => null,
                'year_acquired' => 2013,
                'status' => 'inactive',
                'condition' => 'damaged',
                'length' => 86.13,
                'width' => 146.24,
                'height' => 217.87,
                'power' => '3 HP',
                'supplier' => 'PT Sumber Teknik',
                'image' => null,
                'description' => null,
                'repair_complexity' => 4,
                'created_by' => 1,
            ],
            // Pastikan data yang tersisa dari excel Anda ditambahkan di sini
            // Saya hanya menyertakan 18 baris pertama seperti yang terakhir diolah.
        ];

        foreach ($machines as $machine) {
            // Pilih ID PLP user secara acak dari daftar yang tersedia
            $randomPlpUserId = $plpUserIds[array_rand($plpUserIds)];

            DB::table('machines')->insert([
                'name' => $machine['name'],
                'type' => $machine['type'],
                'code' => $machine['code'],
                'inventory_number' => $machine['inventory_number'],
                'year_acquired' => $machine['year_acquired'],
                'status' => $machine['status'],
                'condition' => $machine['condition'],
                'length' => $machine['length'],
                'width' => $machine['width'],
                'height' => $machine['height'],
                'power' => $machine['power'],
                'supplier' => $machine['supplier'],
                'image' => $machine['image'],
                'description' => $machine['description'],
                'repair_complexity' => $machine['repair_complexity'],
                'created_by' => $randomPlpUserId, // Menggunakan ID PLP user
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]);
        }
    }
}
