<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class MachineSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Pastikan UserSeeder dijalankan terlebih dahulu untuk mengisi data PLP
        // Jika belum yakin, bisa ditambahkan call seeder di sini (tidak disarankan untuk produksi besar)
        // $this->call(UserSeeder::class);

        // Ambil semua ID pengguna dengan role 'plp'
        $plpUserIds = DB::table('users')->where('role', 'plp')->pluck('id')->toArray();

        // Beri peringatan jika tidak ada pengguna PLP yang ditemukan
        if (empty($plpUserIds)) {
            $this->command->warn('Tidak ada pengguna dengan role "plp" ditemukan. Harap jalankan UserSeeder terlebih dahulu atau pastikan pengguna PLP sudah ada.');
            return;
        }

        $machines = [
            [
                'name' => 'MESIN FRAIS FEHLMANN PICOMAX ',
                'type' => 'Picomax',
                'code' => 'FR 21',
                'inventory_number' => null,
                'year_acquired' => 2018,
                'status' => 'active',
                'condition' => 'good',
                'length' => 3.74,
                'width' => 4.85,
                'height' => 6.64,
                'power' => '88 kW',
                'supplier' => 'CV. Jaya Abadi',
                'image' => null,
                'description' => 'oli hidrolik berkualitas tinggi (ISO VG 32 atau 46) untuk sistem hidrolik, pelumasan gear dan bearing spindle, gunakan oli spindle (ISO VG 2 atau 5)',
                'repair_complexity' => 4,
            ],
            [
                'name' => 'MESIN FRAIS LAGUN ',
                'type' => 'Lagun FU.1',
                'code' => 'FR 19',
                'inventory_number' => null,
                'year_acquired' => 2004,
                'status' => 'active',
                'condition' => 'good',
                'length' => 5.72,
                'width' => 4.14,
                'height' => 6.37,
                'power' => '1 kW',
                'supplier' => 'PT. Maju Bersama',
                'image' => null,
                'description' => 'oli hidrolik (ISO VG 32 atau 46) untuk power feed dan clamping,Untuk pelumasan spindle dan gearbox, gunakan oli gear (ISO VG 68 atau 100) atau oli bearing berkualitas tinggi',
                'repair_complexity' => 5,
            ],
            [
                'name' => 'MESIN FRAIS AJAX',
                'type' => 'AJUM 200',
                'code' => 'FR 14',
                'inventory_number' => null,
                'year_acquired' => 1997,
                'status' => 'active',
                'condition' => 'good',
                'length' => 4.89,
                'width' => 1.87,
                'height' => 4.59,
                'power' => '8 kW',
                'supplier' => 'PT. Indotama Mesin',
                'image' => null,
                'description' => 'Oli Tellus-46, Omala-150, tonna-68',
                'repair_complexity' => 3,
            ],
            [
                'name' => 'MESIN FRAIS ACIERA',
                'type' => 'Aciera F3',
                'code' => 'FR 07',
                'inventory_number' => null,
                'year_acquired' => 2010,
                'status' => 'active',
                'condition' => 'good',
                'length' => 3.62,
                'width' => 0.94,
                'height' => 6.53,
                'power' => '88 kW',
                'supplier' => 'PT. Tekindo Unggul',
                'image' => null,
                'description' => 'oli hidrolik (ISO VG 32 atau 46) dan oli gear (ISO VG 68 atau 100',
                'repair_complexity' => 1,
            ],
            [
                'name' => 'MESIN FRAIS FELDMANN',
                'type' => 'Feldmann 01',
                'code' => 'FR 1',
                'inventory_number' => null,
                'year_acquired' => 2008,
                'status' => 'active',
                'condition' => 'good',
                'length' => 6.51,
                'width' => 3.58,
                'height' => 1.53,
                'power' => '63 kW',
                'supplier' => 'CV. Mekanika Prima',
                'image' => null,
                'description' => 'oli hidrolik berkualitas tinggi (ISO VG 32 atau 46) dan oli spindle presisi (ISO VG 2 atau 5) untuk spindle',
                'repair_complexity' => 4,
            ],
            [
                'name' => 'MESIN FRAIS DENBIGH',
                'type' => 'Denbigh H',
                'code' => 'FR 20',
                'inventory_number' => null,
                'year_acquired' => 2006,
                'status' => 'active',
                'condition' => 'good',
                'length' => 6.16,
                'width' => 2.58,
                'height' => 3.09,
                'power' => '66 kW',
                'supplier' => 'PT. Indotama Mesin',
                'image' => null,
                'description' => 'oli hidrolik (ISO VG 32 atau 46) untuk sistem hidrolik, dan oli gear (ISO VG 68 atau 100) untuk gearbox',
                'repair_complexity' => 5,
            ],
            [
                'name' => 'MESIN FRAIS DECKEL',
                'type' => 'FP1',
                'code' => 'FR 08',
                'inventory_number' => null,
                'year_acquired' => 2015,
                'status' => 'active',
                'condition' => 'good',
                'length' => 8.12,
                'width' => 4.63,
                'height' => 5.23,
                'power' => '47 kW',
                'supplier' => 'PT. Tekindo Unggul',
                'image' => null,
                'description' => 'oli spindle (ISO VG 2, 5, atau 10) untuk spindle, oli hidrolik (ISO VG 32 atau 46) untuk sistem hidrolik',
                'repair_complexity' => 2,
            ],
            [
                'name' => 'MESIN GERINDA PERMUKAAN',
                'type' => 'PENG 01',
                'code' => 'GR 01',
                'inventory_number' => null,
                'year_acquired' => 2011,
                'status' => 'active',
                'condition' => 'good',
                'length' => 5.77,
                'width' => 4.7,
                'height' => 4.41,
                'power' => '54 kW',
                'supplier' => 'PT. Maju Bersama',
                'image' => null,
                'description' => 'oli hidrolik (ISO VG 32 atau 46) untuk sistem hidrolik penggerak meja dan pengangkatan spindel, oli slideway (ISO VG 68 atau 220) untuk pelumasan slideway meja dan kolom, dan oli spindel (ISO VG 2, 5, atau 10) untuk spindel',
                'repair_complexity' => 4,
            ],
            [
                'name' => 'MESIN SKRAP',
                'type' => 'SKRAP 01',
                'code' => 'SK 01',
                'inventory_number' => null,
                'year_acquired' => 2010,
                'status' => 'active',
                'condition' => 'good',
                'length' => 1.59,
                'width' => 4.86,
                'height' => 1.45,
                'power' => '72 kW',
                'supplier' => 'CV. Jaya Abadi',
                'image' => null,
                'description' => 'oli gear (ISO VG 68 atau 100) untuk melumasi mekanisme penggerak utama, Untuk pelumasan guideway ram dan meja, gunakan oli pelumas guideway (ISO VG 68 atau CGLP).',
                'repair_complexity' => 2,
            ],
            [
                'name' => 'Case',
                'type' => 'Pass',
                'code' => 'Fail',
                'inventory_number' => null,
                'year_acquired' => 2022,
                'status' => 'inactive',
                'condition' => 'good',
                'length' => 9.54,
                'width' => 3.99,
                'height' => 6.92,
                'power' => '12 kW',
                'supplier' => 'CV. Jaya Abadi',
                'image' => null,
                'description' => '',
                'repair_complexity' => 2,
            ],
            [
                'name' => 'Miling',
                'type' => 'CNC 01',
                'code' => 'FR 02',
                'inventory_number' => null,
                'year_acquired' => 1990,
                'status' => 'active',
                'condition' => 'good',
                'length' => 3.79,
                'width' => 3.96,
                'height' => 3.29,
                'power' => '25 kW',
                'supplier' => 'PT. Indotama Mesin',
                'image' => null,
                'description' => '',
                'repair_complexity' => 5,
            ],
            [
                'name' => 'Miling',
                'type' => 'FR 03',
                'code' => 'FR 03',
                'inventory_number' => null,
                'year_acquired' => 2008,
                'status' => 'active',
                'condition' => 'good',
                'length' => 6.6,
                'width' => 1.5,
                'height' => 6.55,
                'power' => '3 kW',
                'supplier' => 'PT. Maju Bersama',
                'image' => null,
                'description' => '',
                'repair_complexity' => 1,
            ],
            [
                'name' => 'Miling',
                'type' => 'FR 04',
                'code' => 'FR 04',
                'inventory_number' => null,
                'year_acquired' => 2011,
                'status' => 'active',
                'condition' => 'good',
                'length' => 6.22,
                'width' => 3.39,
                'height' => 3.5,
                'power' => '54 kW',
                'supplier' => 'PT. Maju Bersama',
                'image' => null,
                'description' => '',
                'repair_complexity' => 4,
            ],
            [
                'name' => 'Milling',
                'type' => 'FR 05',
                'code' => 'FR 05',
                'inventory_number' => null,
                'year_acquired' => 2004,
                'status' => 'active',
                'condition' => 'good',
                'length' => 5.15,
                'width' => 2.05,
                'height' => 2.45,
                'power' => '97 kW',
                'supplier' => 'CV. Jaya Abadi',
                'image' => null,
                'description' => '',
                'repair_complexity' => 5,
            ],
            [
                'name' => 'Milling',
                'type' => 'FR 06',
                'code' => 'FR 06',
                'inventory_number' => null,
                'year_acquired' => 2009,
                'status' => 'active',
                'condition' => 'good',
                'length' => 1.84,
                'width' => 1.25,
                'height' => 6.74,
                'power' => '89 kW',
                'supplier' => 'CV. Jaya Abadi',
                'image' => null,
                'description' => '',
                'repair_complexity' => 3,
            ],
            [
                'name' => 'Milling',
                'type' => 'FR 09',
                'code' => 'FR 09',
                'inventory_number' => null,
                'year_acquired' => 2003,
                'status' => 'active',
                'condition' => 'good',
                'length' => 1.76,
                'width' => 1.57,
                'height' => 1.83,
                'power' => '39 kW',
                'supplier' => 'CV. Mekanika Prima',
                'image' => null,
                'description' => '',
                'repair_complexity' => 1,
            ],
            [
                'name' => 'Milling',
                'type' => 'FR 10',
                'code' => 'FR 10',
                'inventory_number' => null,
                'year_acquired' => 2013,
                'status' => 'active',
                'condition' => 'good',
                'length' => 4.3,
                'width' => 2.58,
                'height' => 5.56,
                'power' => '47 kW',
                'supplier' => 'PT. Maju Bersama',
                'image' => null,
                'description' => '',
                'repair_complexity' => 4,
            ],
            [
                'name' => 'Milling',
                'type' => 'FR 11',
                'code' => 'FR 11',
                'inventory_number' => null,
                'year_acquired' => 2000,
                'status' => 'active',
                'condition' => 'good',
                'length' => 5.43,
                'width' => 1.34,
                'height' => 2.12,
                'power' => '32 kW',
                'supplier' => 'PT. Maju Bersama',
                'image' => null,
                'description' => '',
                'repair_complexity' => 5,
            ],
            // Pastikan data yang tersisa dari excel Anda ditambahkan di sini
            // Saya hanya menyertakan 18 baris pertama seperti yang terakhir diolah.
        ];

        foreach ($machines as $machine) {
            // Pilih ID PLP user secara acak dari daftar yang tersedia
            $randomPlpUserId = $plpUserIds[array_rand($plpUserIds)];

            DB::table('machines')->insert([
                'name' => $machine['name'],
                'type' => $machine['type'],
                'code' => $machine['code'],
                'inventory_number' => $machine['inventory_number'],
                'year_acquired' => $machine['year_acquired'],
                'status' => $machine['status'],
                'condition' => $machine['condition'],
                'length' => $machine['length'],
                'width' => $machine['width'],
                'height' => $machine['height'],
                'power' => $machine['power'],
                'supplier' => $machine['supplier'],
                'image' => $machine['image'],
                'description' => $machine['description'],
                'repair_complexity' => $machine['repair_complexity'],
                'created_by' => $randomPlpUserId, // Menggunakan ID PLP user
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]);
        }
    }
}
